#이 파일은 github에 올리는 용으로 사용하는 Sample application-oauth2.yml 파일
#실제 사용할 때는 application-oauth2.yml 파일을 작성해서 사용해야 함

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:  #구글 oauth2 서버의 id
                        client-secret:  #구글 oauth2 서버의 pw
                        scope: # 구글에 요청할 정보
                            - profile
                            - email

                    kakao:
                        client-id: # kakao oauth2 서버의 id
                        client-secret:  #kakao oauth2의 secret-id
                        scope:
                            - profile_nickname
                            - account_email
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
                        client-authentication-method: client_secret_post

                    naver:
                        client-id: # naver oauth2 서버의 id
                        client-secret: # naver oauth2 서버의 secret-id
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope:
                            - name
                            - email
                        client-name: Naver
                        client-authentication-method: client_secret_post


                provider:
                    #google은 자동

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response